"""Protocol constants that do not require Home Assistant imports."""

TELEMETRY_OUTER_DPS = (21, 25)

DP_AC_VOLTAGE = 9
DP_AC_CURRENT = 10
DP_AC_FREQUENCY = 11
DP_POWER_FACTOR = 12
DP_ALARM_CODE = 13
DP_OUTPUT_LIMIT = 14
DP_AC_POWER = 15
DP_PV1_VOLTAGE = 16
DP_PV1_CURRENT = 17
DP_PV1_POWER = 18
DP_PV2_VOLTAGE = 19
DP_PV2_CURRENT = 20
DP_PV2_POWER = 21
DP_TEMPERATURE = 28
